blacklistedOres = []
enableNoEmiMessage = true
spawnWithGuideBook = true
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = true
enableHatchPlacementOverlay = true
enableBarrelContentRendering = true
colorWaterLava = true
enableDebugCommands = true
enableBidirectionalEnergyCompat = true
enableAe2Integration = true
enableFtbQuestsIntegration = true
generateOres = false
datagenOnStartup = true
loadRuntimeGeneratedResources = true
removeIndustrialistTrades = true
maxDistillationTowerHeight = 9
