[mimicSettings]
mimicDifficulty = "MEDIUM"
spawnNaturalMimics = false
naturalMimicSpawnRate = 0.3
allowPetMimics = true
doPetMimicLimit = true
petMimicLimit = 2
abandonedMimicTimer = 5
allowPetMimicLocking = true
[worldGen]
potSpawnChance = 0.2
chestSpawnChance = 0.3
surfaceChestSpawnChance = 0.3
secretMimicChance = 0.4
[chestSettings]
allowChestLocking = true
enableLockedChestOwners = true
